export const authActions = {
    SIGNIN_USER_REQUESTED: "SIGNIN_USER_REQUESTED",
    SIGNIN_USER_RECEIVED: "SIGNIN_USER_RECEIVED",
    SIGNIN_USER_FAILED: "SIGNIN_USER_FAILED",
    
    SIGNUP_USER_REQUESTED: "SIGNUP_USER_REQUESTED",
    SIGNUP_USER_RECEIVED: "SIGNUP_USER_RECEIVED",
    SIGNUP_USER_FAILED: "SIGNUP_USER_FAILED",

    SIGNOUT_USER: "SIGNOUT_USER"
};

export const chatActions = {
    GET_CHATS_REQUESTED: "GET_CHATS_REQUESTED",
    GET_CHATS_RECEIVED: "GET_CHATS_RECEIVED",
    GET_CHATS_FAILED: "GET_CHATS_FAILED",

    CREATE_CHAT_REQUESTED: "CREATE_CHAT_REQUESTED",
    CREATE_CHAT_RECEIVED: "CREATE_CHAT_RECEIVED",
    CREATE_CHAT_FAILED: "CREATE_CHAT_FAILED",

    TOGGLE_CREATE_CHAT_CARD: "TOGGLE_CREATE_CHAT_CARD",

    OPEN_CHAT: "OPEN_CHAT"
};

export const messageActions = {
    GET_MESSAGES_REQUESTED: "GET_MESSAGES_REQUESTED",
    GET_MESSAGES_RECEIVED: "GET_MESSAGES_RECEIVED",
    GET_MESSAGES_FAILED: "GET_MESSAGES_FAILED",

    CREATE_MESSAGE_REQUESTED: "CREATE_MESSAGE_REQUESTED",
    CREATE_MESSAGE_RECEIVED: "CREATE_MESSAGE_RECEIVED",
    CREATE_MESSAGE_FAILED: "CREATE_MESSAGE_FAILED"
};
