export const userAuthOps = {
    SIGNIN_USER_REQUESTED: "SIGNIN_USER_REQUESTED",
    SIGNIN_USER_RECEIVED: "SIGNIN_USER_RECEIVED",
    SIGNIN_USER_FAILED: "SIGNIN_USER_FAILED",
    
    SIGNUP_USER_REQUESTED: "SIGNUP_USER_REQUESTED",
    SIGNUP_USER_RECEIVED: "SIGNUP_USER_RECEIVED",
    SIGNUP_USER_FAILED: "SIGNUP_USER_FAILED",
};

export const chatOps = {
    GET_CHATS_REQUESTED: "GET_CHATS_REQUESTED",
    GET_CHATS_RECEIVED: "GET_CHATS_RECEIVED",
    GET_CHATS_FAILED: "GET_CHATS_FAILED"
};
