export const userAuthOps = {
    USER_SIGNIN_REQUESTED: "USER_SIGNIN_REQUESTED",
    USER_SIGNIN_RECEIVED: "USER_SIGNIN_RECEIVED",
    USER_SIGNIN_FAILED: "USER_SIGNIN_FAILED",
    
    USER_SIGNUP_REQUESTED: "USER_SIGNUP_REQUESTED",
    USER_SIGNUP_RECEIVED: "USER_LOGIN_RECEIVED",
    USER_SIGNUP_FAILED: "USER_SIGNUP_FAILED",
    
    GET_CURRENT_USER_REQUESTED: "GET_CURRENT_USER_REQUESTED",
    GET_CURRENT_USER_RECEIVED: "GET_CURRENT_USER_RECEIVED",
    GET_CURRENT_USER_FAILED: "GET_CURRENT_USER_FAILED"
};

export const chatOps = {
    GET_CHATS_LIST_REQUESTED: "GET_CHATS_LIST_REQUESTED",
    GET_CHATS_LIST_RECEIVED: "GET_CHATS_LIST_RECEIVED",
    GET_CHATS_LIST_FAILED: "GET_CHATS_LIST_FAILED"
};
